version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres

  api:
    build: 
      context: ./be
    volumes:
      - ./be:/app
    ports:
      - 8000:8000

  client:
    build:
      context: ./fe
    volumes:
      - ./fe:/app
    ports:
      - 3000:3000
